# fly.toml app configuration file generated for flyio-server3001 on 2024-01-07T14:26:42+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "flyio-server3001"
primary_region = "nrt"

[build]

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
